### ISSUE TITLE
[JOSS] Unable to run demo tool

### ISSUE THREAD

**Issue by nick-gorman** [SESMG/SESMG#190]
**Code of Conduct**
- [x] Hereby I consent to the [CODE_OF_CONDUCT](https://github.com/SESMG/SESMG/blob/master/CODE_OF_CONDUCT.md)

**Describe the bug**

**To Reproduce**
1. Go to Demo Tool
2. Change Ground coupled heat pump to 24 kW
3. Change District Heating Network to Urban
4. Click Start Simulation

**Expected behavior**
Not sure what should happen, but nothing does. In the cmd window an error appears, see below.

```
INFO:root:Cartopy is not installed. Background maps will not be drawn.
20:48:32-INFO-Path for logging: C:\Users\nick\Documents\GitHub\SESMG\results\demo\oemof.log
20:48:35-INFO-   Spreadsheet scenario successfully imported.
20:48:35-INFO-   Start import weather data
2023-06-26 20:48:35.118 Uncaught app exception
Traceback (most recent call last):
  File "C:\Users\nick\Documents\GitHub\SESMG\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 552, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\nick\Documents\GitHub\SESMG\program_files\GUI_st\pages\4_Demo_Tool.py", line 365, in <module>
    create_demo_model_definition()
  File "C:\Users\nick\Documents\GitHub\SESMG\program_files\GUI_st\pages\4_Demo_Tool.py", line 258, in create_demo_model_definition
    execute_sesmg_demo(
  File "C:\Users\nick\Documents\GitHub\SESMG\program_files\GUI_st\pages\4_Demo_Tool.py", line 181, in execute_sesmg_demo
    sesmg_main(
  File "C:\Users\nick\Documents\GitHub\SESMG\program_files\preprocessing\Spreadsheet_Energy_System_Model_Generator.py", line 77, in sesmg_main
    nodes_data = create_energy_system.import_model_definition(
  File "C:\Users\nick\Documents\GitHub\SESMG\program_files\preprocessing\create_energy_system.py", line 82, in import_model_definition
    nodes_data = import_open_fred_weather_data(nodes_data, lat, lon)
  File "C:\Users\nick\Documents\GitHub\SESMG\program_files\preprocessing\import_weather_data.py", line 71, in import_open_fred_weather_data
    geo_info = geocoder.osm([lat, lon], method='reverse')
  File "C:\Users\nick\Documents\GitHub\SESMG\lib\site-packages\geocoder\api.py", line 458, in osm
    return get(location, provider='osm', **kwargs)
  File "C:\Users\nick\Documents\GitHub\SESMG\lib\site-packages\geocoder\api.py", line 198, in get
    return options[provider][method](location, **kwargs)
  File "C:\Users\nick\Documents\GitHub\SESMG\lib\site-packages\geocoder\base.py", line 395, in __init__
    self.params = OrderedDict(self._build_params(location, provider_key, **kwargs))
  File "C:\Users\nick\Documents\GitHub\SESMG\lib\site-packages\geocoder\osm_reverse.py", line 25, in _build_params
    'q': str(Location(location)),
  File "C:\Users\nick\Documents\GitHub\SESMG\lib\site-packages\geocoder\location.py", line 22, in __init__
    self._check_input(location)
  File "C:\Users\nick\Documents\GitHub\SESMG\lib\site-packages\geocoder\location.py", line 53, in _check_input
    self._check_for_list(location)
  File "C:\Users\nick\Documents\GitHub\SESMG\lib\site-packages\geocoder\location.py", line 88, in _check_for_list
    raise ValueError(
ValueError: Coords are not within the world's geographical boundary
```

**Screenshots**
![image](https://github.com/SESMG/SESMG/assets/40549624/6601fb4b-4d5c-48fb-b875-7aa756751951)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: v0.5.0

**Additional context**
When I installed SESMG I also got the error message described in #189

**Comment by chrklemm** [comment]
Dear @nick-gorman,

thank you very much for your contribution. We have tried to reproduce this error. We only managed to do this by modifying the following file: "SESMG/program_files/demo_tool/v0.4.0_demo_model_definition/demo_model_definition.xlsx"

The demo tool and the associated model definition are a self-contained system and it is not intended to modify the related files. Changes in the demo tool are made by the user through the GUI only. All other models, which are started on the "main page" of the gui, for example "SESMG/model_definition_example.xlsx" may be adapted.

Can you provide the following information so that we can follow up on the issue?
- Which Python version are you using?
- Are you using the SESMG version from the main branch?
- Have you modified this file ("SESMG/program_files/demo_tool/v0.4.0_demo_model_definition/demo_model_definition.xlsx")?
- Did you manually change or reinstall packages, e.g. to solve Issue #189?

Thank you in advance and best regards,
SESMG-Dev-Team

**Comment by nick-gorman** [comment]
@chrklemm 

- I'm using python 3.8
- Using master branch as of commit: 27b0e8e177c3e75bdde19df3ec6c457f0fa04d51
- No, I have not modified the file "SESMG/program_files/demo_tool/v0.4.0_demo_model_definition/demo_model_definition.xlsx"
- No didn't do any manual install process, just cloned the repo, installed graphviz, got the cbc binaries, and ran the install cmd file

Would appreciate any further suggestions

**Comment by jtock** [comment]
Hi @nick-gorman,

we figured out that there is an incompatibility between some versions of python 3.8 and some sub packages we are using. E.g. we were able to reproduce your issue with the python version 3.8.4 to 3.8.7, due to an incompatibility issue with pandas during the import of xlsx-files. 

The installation and program is running normally with the python versions we are usually using, which are e.g. 3.8.10 or 3.9.13.

We are working on a way to automatically test the Python subversions, to determine if there are more incompatibilities. If you want to continue your review you could use the most extensively tested version 3.9.13, till we come up with a satisfactory solution. 

Greeting 
SESMG Dev Team

**Comment by GregorBecker** [comment]
Hello @nick-gorman,

we have now been able to reproduce your error, and have discovered that it is caused by the new release of pandas 2.0., which is automatically  installed in some Python versions. As a result, we have now removed this version from the suitable requirements (pandas < 2.0.0), ensuring that functionality is restored.

Your issue should be solved by installing the SESMG again from scratch. If this is not the case, please contact us again.

Kind regards 
SESMG Dev Team

**Comment by nick-gorman** [comment]
@GregorBecker Yep! the issue is now fixed, thanks for your help :)
